### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by armangido** [tim4724/StagePresenter-for-ProPresenter#4]
Browser: Google Chrome
OS: Android
Issue: I tried using the option "Connec to ProPresenter on another computer", inputted the internal ip address (eg. 192.168.1.xxx) of the computer which the ProPresenter 7 is currently running clicked the Test Connection and Start nothing seems to happen, when I intercepted the traffic nothing seems to happen

**Comment by tim4724** [comment]
Just to clarify. You have clicked on "Try it now" on the webpage "stagepresenter.com" on an Android device? 

I think the issue was that the page was served with HTTPS, but the connection to ProPresenter is a non secure WebSocket connection. And Chrome does not allow that. (Same problem here https://stackoverflow.com/questions/9745249/websocket-with-ssl)

I have updated the webserver config to serve certain pages using http only. Can you please try again and report back?

**Comment by armangido** [comment]
Version: 7.8.2

It seems working now, I have another problem on stagepresenter it doesn't seem to received or show the Bible message even though I can see it on stage screen
