### ISSUE TITLE
Idea: any way to read 'name' of text fields in a slide to customize display on StageDisplay?

### ISSUE THREAD

**Issue by zvuc** [tim4724/StagePresenter-for-ProPresenter#6]
In our church, we show supplementary english lyrics under main lyrics when available.
The song slides would have two textboxes, first one being the main and second being sub.

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/2870726/205225120-4e3ad375-1bd1-498e-8114-e623eaa107ca.png">

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/2870726/205225085-34abddd0-15a8-4b35-903f-27618181b1bb.png">

The "Only Include the first Textbox of each slide", is a very neat feature that we use daily, because our singers almost always will sing in main language (Korean) and we can keep the stage display simple by only showing the first (main) textbox contents.

A little hassle is that, when we're showing anything other than song lyrics, we have to manually toggle on/off the "first textbox-only" option.

I don't know how much data ProPresenter gives through the API but if the 'textbox' names are also provided and StagePresenter could add these onto the HTML DOM as attributes or classes, I could hook them with CSS to customize display.

For example, if I have two textboxes in a slide and they are named "Main Lyrics" and "Sub Lyrics" respectively, I could use the custom CSS settings in StagePresenter to only hide sub lyrics:

```
.slide[data-name="Sub Lyrics"] {
	display: none;
}
```

Or I could have my own naming conventions for hiding specific textboxes just from StagePresenter:

```
.slide[data-name*="(Hidden)"] {
	display: none;
}
```

Just thought this could be a neat idea that could further lessen another thing the media team has to remember doing during live service :D

Thanks again for creating & maintaining such a wonderful solution, we are greatly benefiting from this app every day 🙏

**Comment by tim4724** [comment]
Thank you for the input. 👍 And great idea with the textbox name. Sadly ProPresenter does not share the textbox names through its API. 

I have another idea for improving the situation. It is possible to configure a label for a slide in ProPresenter. And I am thinking of defining labels like '$stagepresenter:showAllTextBoxes' or '$stagepresenter:showOnlyFirstTextBox' which override the "Only Include the first Textbox of each slide" setting. 
I think this will be a convenient solution because it is possible to select multiple slides in ProPresenter and change the label for the selected slides with one click. 

Actually I already have defined some "special" labels already. I was planning for some time to create a document explaining the different possible labels.

**Comment by zvuc** [comment]
Using labels sounds like a good idea too! Please let me know when the feature + instructions on how to use it is available 👍

**Comment by tim4724** [comment]
The version 0.4.9 in the Mac AppStore contains the new functionality. The website was updated as well.

You can add a label containing `$stagepresenter:showAllTextBoxes` to certain slides and all textboxes will be visible even if "Only include the first Textbox of a Slide" is selected.

There are more labels and other tips in this [Tips and Tricks document](https://github.com/tim4724/StagePresenter-for-ProPresenter/blob/main/tips_and_tricks.md). 

Please let me know if this is a suitable solution with your workflow and setup. :)

**Comment by zvuc** [comment]
I just tried utilizing this today at our service. It worked great! 
![image](https://user-images.githubusercontent.com/2870726/206888579-06431fe9-c5d2-4cd7-b4ea-45a8ed52c88e.png)

One thing though, since Propresenter doesn't natively support selecting 'multiple' labels, I had to manually type the labels — so I was thinking if the labels could be shorter it could be easier to type :) 

Perhaps something shorter like `$sp:showAllTextBoxes` could work? (Chaining could be also a way to shorten multiple StagePresenter specific labels... `$sp:showAllTextBoxes:keepLineBreaks`

Also another idea for forced option: `$stagepresenter:bible`

I noticed that the "Only show first textbox" option is ignored for slides detected as scripture passages, but sometimes when we have non-standard notations (eg: John 1:2**b**) it seems StagePresenter doesn't recognize it as bible. A forced option label could be handy.

**Comment by tim4724** [comment]
Good to hear it worked for you so far 👍 

Thanks for your ideas to further improve the labels. 
- I wanted to have "stagepresenter" in the name of the label, because then it is clear which application is using the label. If someone is wondering about the weird labels in a presentation he maybe will search for "stagepresenter" on Google. 
- I like your idea to combine multiple labels. :)
- I was also thinking about having a label that applies to all slides in a presentation. At the moment I see the following options: Either have a keyword in the presentations title oder have a special label on the first slide.

However I have to sleep on this subject for a (few) day(s) before making plans.

**Comment by tim4724** [comment]
> Also another idea for forced option: $stagepresenter:bible
> 
> I noticed that the "Only show first textbox" option is ignored for slides detected as scripture passages, but sometimes when we have non-standard notations (eg: John 1:2b) it seems StagePresenter doesn't recognize it as bible. A forced option label could be handy.
> 

Yes the "Only show first textbox" option is ignored because of the "Improve Layout of Bible Presentations" option in settings.

I can fix the issue for notations like "John 1:2b". This would be my preferred solution for all issues like this.
@zvuc Do you have other examples where a bible passage was not correctly detected? If you want you can also share some presentations.

But in the case where a bible passage is not correctly recognized... I am guessing the desired effect of a label like "$stagepresenter:bible" would be the following:
- Show either all textboxes, or the one with the longer text (if there are two textboxes).
- Try to recognize the verse numbers and show them in yellow? 

I will think about this '$stagepresenter:bible' label topic. Maybe there is an easy way to use such a label.

**Comment by zvuc** [comment]
> Do you have other examples where a bible passage was not correctly detected? If you want you can also share some presentations.

Another example I can think of could be when we attaching bible translation version symbols at the end? (+combinations of a/b partial scripture)
> John 1:1b (NASB)
> John 1:1 MSG
> John 1:1 (Paraphrased)
> 요한복음 1:1-2 (쉬운성경)
> 요한복음 1:1-2b 새번역

If everything's recognized automatically + correctly that would be the best way but the `$stagepresenter:bible` option sounds like a good manual fallback too.

> Try to recognize the verse numbers and show them in yellow. 
Regarding this, I also did notice that only the first verse numbering would be colored yellow when the following verses are all in same line (no line breaks between verses)

>**1**태초에 말씀이 계시니라 이 말씀이 하나님과 함께 계셨으니 이 말씀은 곧 하나님이시니라 2그가 태초에 하나님과 함께 계셨고 3만물이 그로 말미암아 지은바 되었으니 지은 것이 하나도 그가 없이는 된 것이 없느니라 4그 안에 생명이 있었으니 이 생명은 사람들의 빛이라 5빛이 어두움에 비취되 어두움이 깨닫지 못하더라

In above case only 1 would be colored yellow.
But I'm guessing that it's probably impossible to detect numbers that are not first letters of line... because there could be cases where numbers are included in-verse that are not actually verse numbers? (not sure though..) 🤔

**Comment by zvuc** [comment]
This is awesome 👏👏 Thanks for this, I'll share this to the team. Will report if we encounter any problems.
